name: dariaskripka_
favicon: null
layout_spectrum: 0.7896113349124789
typography_spectrum: 0.4317916613072157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.17374220909550786
  lightness: 0.5891940360888839
  saturation: 0.10061790538020432
  rhythmicContrast: 0.27677962579764426
purpose: []
